Repository ezsystems/ezplatform-user, pull requests merged in 2019-06, with the labels that each got.

#31 EZP-30503: Change names of parameters
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
  src/bundle/Resources/views/change_password/index.html.twig
  src/bundle/Resources/views/change_password/success.html.twig
  src/bundle/Resources/views/forgot_password/index.html.twig
  src/bundle/Resources/views/forgot_password/mail/forgot_user_password.html.twig
  src/bundle/Resources/views/forgot_password/success.html.twig
  src/bundle/Resources/views/forgot_password/with_login.html.twig
  src/bundle/Resources/views/register/register_confirmation.html.twig
  src/bundle/Resources/views/reset_password/index.html.twig
  src/bundle/Resources/views/reset_password/invalid_link.html.twig
  src/bundle/Resources/views/reset_password/success.html.twig
  src/bundle/Resources/views/user-profile/change_user_password.html.twig
  src/bundle/Resources/views/user_settings/list.html.twig
  src/bundle/Resources/views/user_settings/update.html.twig
Labels: Improvement, Ready for review

#38 EZP-30553: User settings pagination limit should be different for admin_group and other siteaccesses
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/EzPlatformUserBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Bug, QA approved

#37 EZP-30570: Upgrade `ezsystems/ezplatform-user` to use Symfony 4 components
  composer.json
  src/bundle/Controller/PasswordResetController.php
  src/bundle/DependencyInjection/EzPlatformUserExtension.php
  src/bundle/EzPlatformUserBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/bundle/Resources/config/services/validators.yaml
  src/bundle/Resources/config/validation.yaml
  tests/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php
  tests/lib/Validator/Constraint/UserPasswordValidatorTest.php
Labels: Improvement
