Repository ezsystems/ezplatform-user, pull requests merged in 2019-03, with the labels that each got.

#7 Added php-cs-fixer to dev dependencies
  composer.json
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Controller/UserRegisterController.php
  src/lib/ConfigResolver/RegistrationContentTypeLoader.php
  src/lib/ConfigResolver/RegistrationGroupLoader.php
  src/lib/Form/Data/UserRegisterData.php
  src/lib/Form/Processor/UserRegisterFormProcessor.php
  src/lib/Form/Type/UserRegisterType.php
  src/lib/View/Register/ConfirmView.php
  src/lib/View/Register/FormView.php
Labels: enhancement

#11 EZP-30099: Define preferred user date format
  src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php
  src/bundle/EzPlatformUserBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/forms.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/translations/user_settings.en.xliff
  src/lib/Form/DataTransformer/DateTimeFormatTransformer.php
  src/lib/Form/Type/UserSettings/DateTimeFormatType.php
  src/lib/Form/Type/UserSettings/FullDateTimeFormatType.php
  src/lib/Form/Type/UserSettings/ShortDateTimeFormatType.php
  src/lib/Templating/Twig/DateTimeExtension.php
  src/lib/UserSetting/Setting/AbstractDateTimeFormat.php
  src/lib/UserSetting/Setting/CharacterCounter.php
  src/lib/UserSetting/Setting/DateTimeFormatSerializer.php
  src/lib/UserSetting/Setting/FullDateTimeFormat.php
  src/lib/UserSetting/Setting/ShortDateTimeFormat.php
  src/lib/UserSetting/Setting/Value/DateTimeFormat.php
Labels: Feature

#10 EZP-30224: Make `ez_user_settings` twig global load user settings dynamically
  src/bundle/Resources/config/services/user_settings.yml
  src/lib/UserSetting/UserSetting.php
  src/lib/UserSetting/UserSettingArrayAccessor.php
Labels: enhancement

#12 EZP-30099: Wrong label in user preferences list for full/short date format
  src/lib/Form/Type/UserSettings/DateTimeFormatType.php
  src/lib/UserSetting/Setting/AbstractDateTimeFormat.php
  src/lib/UserSetting/Setting/FullDateTimeFormat.php
  src/lib/UserSetting/Setting/ShortDateTimeFormat.php
Labels: bug

#14 EZP-30099: Lazy initialize date formatters in \EzSystems\EzPlatformUser\Templating\Twig\DateTimeExtension
  src/bundle/Resources/config/services.yml
  src/lib/Templating/Twig/DateTimeExtension.php
Labels: bug

#16 Added configuration for the jms_translation extension
  src/bundle/DependencyInjection/EzPlatformUserExtension.php
Labels: enhancement

#19 Added Pull request template
  .github/pull_request_template.md
Labels: Improvement, Ready for review

#17 EZP-30253: Reorder the "My Preferences" options under User settings
  src/bundle/DependencyInjection/Compiler/UserSetting/ValueDefinitionPass.php
  src/bundle/Resources/config/services/user_settings.yml
  src/lib/UserSetting/ValueDefinitionRegistry.php
  src/lib/UserSetting/ValueDefinitionRegistryEntry.php
Labels: Bug, QA approved, Ready for review

#18 EZP-30250 Change the date format dropdown option for Long Date & Time format
  src/bundle/Resources/config/ezplatform_default_settings.yml
Labels: Bug, QA approved, Ready for review

#20 EZP-30252: Entire selected time format not displayed under User Settings > My Preferences tab
  src/lib/UserSetting/Setting/FullDateTimeFormat.php
  src/lib/UserSetting/Setting/ShortDateTimeFormat.php
Labels: Bug, Ready for QA, Ready for review

#21 EZP-30251: Display the rendering of time & date when editing the Short/Long Date & Time format
  src/bundle/Controller/UserSettingsController.php
  src/bundle/DependencyInjection/Compiler/UserSetting/ViewBuilderRegistryPass.php
  src/bundle/DependencyInjection/Configuration/Parser/UserSettingsUpdateView.php
  src/bundle/EzPlatformUserBundle.php
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/bundle/Resources/views/user_settings/update.html.twig
  src/lib/View/UserSettings/Matcher/Identifier.php
  src/lib/View/UserSettings/UpdateView.php
  src/lib/View/UserSettings/UpdateViewBuilder.php
  src/lib/View/UserSettings/UpdateViewProvider.php
Labels: Bug, Feature, QA approved

#22 EZP-30306: Translation for User Setting Language is missing.
  src/bundle/Resources/translations/user_change_password.en.xliff
  src/bundle/Resources/translations/user_settings.en.xliff
  src/lib/UserSetting/Setting/Language.php
Labels: Bug, Ready for review

#23 EZP-30303: Internal Sever Error when changing Time Zone
  src/bundle/Controller/UserSettingsController.php
Labels: QA approved

#25 EZP-30292: Wrong label for displaying Time in User Settings
  src/bundle/Resources/translations/user_settings.en.xliff
  src/lib/Form/Type/UserSettings/DateTimeFormatType.php
Labels: Bug, QA approved, Ready for review

#24 EZP-30248 Display the current date & time in the selected format on the User settings > My Preferences tab for both Long and short date & time format
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/lib/Templating/Twig/DateTimeExtension.php
  src/lib/UserSetting/DateTimeFormat/AbstractDateTimeFormatterFactory.php
  src/lib/UserSetting/DateTimeFormat/DateTimeFormatterFactoryInterface.php
  src/lib/UserSetting/DateTimeFormat/Formatter.php
  src/lib/UserSetting/DateTimeFormat/FormatterInterface.php
  src/lib/UserSetting/DateTimeFormat/FullDateTimeFormatterFactory.php
  src/lib/UserSetting/DateTimeFormat/ShortDateTimeFormatterFactory.php
  src/lib/UserSetting/Setting/AbstractDateTimeFormat.php
  src/lib/UserSetting/Setting/FullDateTimeFormat.php
  src/lib/UserSetting/Setting/ShortDateTimeFormat.php
Labels: Bug, Feature, QA approved, Ready for review

#26 EZP-30263: User date format don't apply to date fields in content item update and preview
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Resources/config/services/user_settings.yml
  src/lib/Templating/Twig/DateTimeExtension.php
  src/lib/UserSetting/DateTimeFormat/Formatter.php
  src/lib/UserSetting/DateTimeFormat/FormatterInterface.php
  src/lib/UserSetting/DateTimeFormat/FullDateFormatterFactory.php
  src/lib/UserSetting/DateTimeFormat/FullTimeFormatterFactory.php
  src/lib/UserSetting/DateTimeFormat/ShortDateFormatterFactory.php
  src/lib/UserSetting/DateTimeFormat/ShortTimeFormatterFactory.php
Labels: Bug, Feature, QA approved, Ready for review
