Repository ezsystems/ezplatform-user, pull requests merged in 2019-05, with the labels that each got.

#32 EZP-30514: Moved default configuration to dedicated ViewProvider for the user_settings_update_view
  src/bundle/Resources/config/ezplatform_default_settings.yml
  src/bundle/Resources/config/services/user_settings.yml
Labels: Bug

#33 Fixed multiple issues in user_settings/update.html.twig template
  src/bundle/Resources/views/user_settings/update.html.twig
Labels: Bug

#28 EZP-30400: Inject TranslationService into NotificationService
  src/bundle/Controller/PasswordChangeController.php
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Controller/UserSettingsController.php
  src/lib/Validator/Constraints/UserPassword.php
Labels: Improvement, QA approved, Ready for MERGE, Ready for review

#34 Value definitions passed to the ValueDefinitionRegistry constructor should be available in the registry
  src/lib/UserSetting/ValueDefinitionRegistry.php
  tests/lib/UserSetting/ValueDefinitionRegistryTest.php
Labels: Bug, Ready for MERGE

#35 Fixed multiple issues in user_settings/list.html.twig template
  src/bundle/Resources/views/user_settings/list.html.twig
Labels: Bug, QA approved, Ready for MERGE

#30 EZP-30417: Display password reset form validation errors
  src/bundle/Controller/PasswordResetController.php
  src/lib/Form/Data/UserPasswordResetData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/UserPasswordResetType.php
Labels: Bug, QA approved

#36 EZP-30552: Fixed the User settings pagination
  src/lib/UserSetting/UserSettingService.php
  src/lib/UserSetting/ValueDefinitionRegistry.php
  tests/lib/UserSetting/UserSettingServiceTest.php
  tests/lib/UserSetting/ValueDefinitionRegistryTest.php
Labels: Bug, Ready for QA

#29 EZP-30473: Renaming and moving templates
  src/bundle/Resources/views/user_settings/update.html.twig
Labels: Improvement, Ready for review
