Repository ezsystems/ezplatform-user, pull requests merged in 2020-03, with the labels that each got.

#63 EZP-31220: Migrated codebase to Symfony 5
  composer.json
  src/lib/Form/ChoiceList/Loader/AvailableLocaleChoiceLoader.php
  src/lib/UserSetting/Setting/CharacterCounter.php
  src/lib/UserSetting/Setting/FullDateTimeFormat.php
  src/lib/UserSetting/Setting/Language.php
  src/lib/UserSetting/Setting/ShortDateTimeFormat.php
  src/lib/UserSetting/Setting/SubitemsLimit.php
  src/lib/UserSetting/Setting/Timezone.php
Labels: Ready for MERGE

#64 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  composer.json
Labels: Improvement

#62 EZP-31079: Provided validation for email uniqueness and login pattern
  src/bundle/Command/AuditUserDatabaseCommand.php
  src/bundle/Resources/config/services.yaml
Labels: QA approved
