Repository ezsystems/ezplatform-user, pull requests merged in 2020-04, with the labels that each got.

#65 EZP-30965: Fixed type error in UserMenuListener
  src/bundle/Resources/config/services.yml
  src/lib/EventListener/UserMenuListener.php
Labels: QA approved

#68 EZP-31536: Fixed invalid \Twig\Environment::loadTemplate method call
  src/bundle/Controller/PasswordResetController.php
Labels: Bug

#69 EZP-30543: Removed Dynamic Settings functionality from kernel
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Controller/UserSettingsController.php
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/lib/ConfigResolver/ConfigurableRegistrationGroupLoader.php
  src/lib/EventListener/ViewTemplatesListener.php
  src/lib/Form/Type/UserSettings/FullDateTimeFormatType.php
  src/lib/Form/Type/UserSettings/ShortDateTimeFormatType.php
  src/lib/UserSetting/Setting/SubitemsLimit.php
Labels: Improvement

#59 EZP-31195: Set From to swiftmailer when From in twig is empty. Set Fr…
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Resources/config/services/controllers.yml
  src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
  src/bundle/Resources/views/forgot_password/mail/forgot_user_password.html.twig
Labels: Bug, QA approved

#70 EZP-31017: Added Password Validator to change password form
  src/bundle/Controller/PasswordChangeController.php
  src/bundle/Controller/PasswordResetController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services/validators.yaml
  src/lib/Form/Data/UserPasswordResetData.php
  src/lib/Form/Data/UserRegisterData.php
  src/lib/Form/Factory/FormFactory.php
  src/lib/Form/Type/UserPasswordChangeType.php
  src/lib/Form/Type/UserPasswordResetType.php
  src/lib/Validator/Constraints/Password.php
  src/lib/Validator/Constraints/PasswordValidator.php
  tests/lib/Validator/Constraint/PasswordTest.php
  tests/lib/Validator/Constraint/PasswordValidatorTest.php
Labels: QA approved
